2023-07-01 20:35:12,907 - ERROR - 'Message' object has no attribute 'date123'
Traceback (most recent call last):
  File "c:/Dev/leetcode/tg_bot.py", line 23, in handle_message
    message_date = message.date123
AttributeError: 'Message' object has no attribute 'date123'
2023-07-01 20:35:44,168 - ERROR - 'Message' object has no attribute 'date123'
Traceback (most recent call last):
  File "c:/Dev/leetcode/tg_bot.py", line 23, in handle_message
    message_date = message.date123
AttributeError: 'Message' object has no attribute 'date123'
